//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urbagestion.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Urbagestion_Model_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Urbagestion_Model_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Urbagestion.Model.Urbagestion.Model.Resource", typeof(Urbagestion_Model_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalación no válida..
        /// </summary>
        internal static string Reservation_Facility_NotNull {
            get {
                return ResourceManager.GetString("Reservation_Facility_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de la reserva no puede ser anterior a hoy..
        /// </summary>
        internal static string Reservation_ReservationDate_NotInPast {
            get {
                return ResourceManager.GetString("Reservation_ReservationDate_NotInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora de inicio no puede ser posterior ni igual a la hora de fin.
        /// </summary>
        internal static string Reservation_StartsNotGreaterThanEnds {
            get {
                return ResourceManager.GetString("Reservation_StartsNotGreaterThanEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no válido..
        /// </summary>
        internal static string Reservation_User_NotNull {
            get {
                return ResourceManager.GetString("Reservation_User_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar una hora de apertura..
        /// </summary>
        internal static string SharedResource_OpensAt_NotNull {
            get {
                return ResourceManager.GetString("SharedResource_OpensAt_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar un nombre..
        /// </summary>
        internal static string SharedResources_Name_NotNull {
            get {
                return ResourceManager.GetString("SharedResources_Name_NotNull", resourceCulture);
            }
        }
    }
}
