//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urbagestion.UI.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Urbagestion.UI.Web.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternar navegación.
        /// </summary>
        public static string _Layout_ToogleNavigation {
            get {
                return ResourceManager.GetString("_Layout_ToogleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre debe tener un mínimo de 5 caracteres..
        /// </summary>
        public static string Facility_NameMinLen {
            get {
                return ResourceManager.GetString("Facility_NameMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicacion para la gestión de recursos comunitarios..
        /// </summary>
        public static string HomeController_About {
            get {
                return ResourceManager.GetString("HomeController_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar.
        /// </summary>
        public static string HomeController_Book {
            get {
                return ResourceManager.GetString("HomeController_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to somecontact@domain.com.
        /// </summary>
        public static string HomeController_Contact {
            get {
                return ResourceManager.GetString("HomeController_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string HomeController_Home {
            get {
                return ResourceManager.GetString("HomeController_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado por:.
        /// </summary>
        public static string ModelBase_CreatedByLabel {
            get {
                return ResourceManager.GetString("ModelBase_CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de creación:.
        /// </summary>
        public static string ModelBase_CreationdDateLabel {
            get {
                return ResourceManager.GetString("ModelBase_CreationdDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador inválido..
        /// </summary>
        public static string ModelBase_IdMinusCero {
            get {
                return ResourceManager.GetString("ModelBase_IdMinusCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo:.
        /// </summary>
        public static string ModelBase_IsActiveLabel {
            get {
                return ResourceManager.GetString("ModelBase_IsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizado por:.
        /// </summary>
        public static string ModelBase_UpdatedDateLabel {
            get {
                return ResourceManager.GetString("ModelBase_UpdatedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalación no válida..
        /// </summary>
        public static string Reservation_Facility_NotNull {
            get {
                return ResourceManager.GetString("Reservation_Facility_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de la reserva no puede ser anterior a hoy..
        /// </summary>
        public static string Reservation_ReservationDate_NotInPast {
            get {
                return ResourceManager.GetString("Reservation_ReservationDate_NotInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora de inicio no puede ser posterior ni igual a la hora de fin.
        /// </summary>
        public static string Reservation_StartsNotGreaterThanEnds {
            get {
                return ResourceManager.GetString("Reservation_StartsNotGreaterThanEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no válido..
        /// </summary>
        public static string Reservation_User_NotNull {
            get {
                return ResourceManager.GetString("Reservation_User_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar una hora de cierre..
        /// </summary>
        public static string SharedResource_CloseAt_NotNull {
            get {
                return ResourceManager.GetString("SharedResource_CloseAt_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora de apertura no puede ser igual o anterior a la de cierre..
        /// </summary>
        public static string SharedResource_OpensAt_NotGreather_CloseAt {
            get {
                return ResourceManager.GetString("SharedResource_OpensAt_NotGreather_CloseAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar una hora de apertura..
        /// </summary>
        public static string SharedResource_OpensAt_NotNull {
            get {
                return ResourceManager.GetString("SharedResource_OpensAt_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar un nombre..
        /// </summary>
        public static string SharedResources_Name_NotNull {
            get {
                return ResourceManager.GetString("SharedResources_Name_NotNull", resourceCulture);
            }
        }
    }
}
